### ISSUE TITLE
Support for SotFS?

### ISSUE THREAD

**Issue by Balkenkreuz** [PeterTh/gedosato#280] opened 2015-04-04 23:06 UTC
Just wondering if we'll get support added for Scholar of the first sin. Cheers.

**Comment by karasuhebi** [comment] 2015-04-05 06:25
Seeing as how Dark Souls II works just fine using the generic plugin, we should be able to get support pretty easily. It might just be a matter of copying over the DarkSoulsII GeDoSaTo.ini and putting it in a folder named after the SotFS executable and then adding the executable name to the whitelist. I would test it myself but I don't own the game just yet. Waiting for a sale. :)

**Comment by Balkenkreuz** [comment] 2015-04-05 06:53
Yeah though the thing is they share the same .exe name haha DarkSoulsII

**Comment by karasuhebi** [comment] 2015-04-05 06:55
Oh I see. Interesting. So maybe it'll just work without you doing anything?

**Comment by Balkenkreuz** [comment] 2015-04-05 06:59
No that's why i want support added for it :P

**Comment by karasuhebi** [comment] 2015-04-05 07:02
Oh I forgot SotFS is DirectX 11. GeDoSaTo only supports DirectX 9. That's probably why. Let's hope @PeterTh comes back and wants to work on this. I would imagine it would require quite a bit of work to make GeDoSaTo DirectX 11-compatible.

**Comment by Balkenkreuz** [comment] 2015-04-05 07:03
Yeah that's what i'm hoping for. Sucks not having all my custom textures

**Comment by avandius** [comment] 2015-05-06 00:34
I've tried to port over certain effects such as bloom, but I'm not having much luck. I love many of the changes in SotFS but really miss those awesome GeDoSaTo effects (particularly it's bloom algorithm). 

If @PeterTh gets it working, there will definitely be donations!

**Comment by PeterTh** [comment] 2015-05-06 08:10
As I said in the other issue, this is a duplicate of https://github.com/PeterTh/gedosato/issues/23.

**Closed by PeterTh** 2015-05-06 08:10 UTC
