### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ZedGates** [PeterTh/gedosato#309] opened 2015-10-14 10:03 UTC
Latest version of GeDoSaTo (Beta 18) not working anymore for me, it was working before (Beta 17). Now I can't even launch any program and/or game with GeDoSaTo open.

**Comment by navjack** [comment] 2015-10-17 05:07
i'll 2nd this. NOTHING works. infact everything seems to be hooked into with the dll now. msi afterburner. steam itself. corsair link... raptr. everything

**Comment by Murd3rTr0n** [comment] 2015-10-17 18:43
Can confirm, after updating to the Disharmonized Genesis build, I cannot get any game to launch whatsoever while GeDoSaTo is running. And, forgive me if I'm ignorant, but I can't find anywhere to download the old version and I would have thought having old builds available for download would be standard procedure.

**Comment by PeterTh** [comment] 2015-10-18 08:55
I've gone over all the changes from 0.17 to 0.18 and I just don't see what could cause any difference in the hooking behavior. I also can't reproduce it locally.

The only thing I can think of is something going wrong with the update...

**Comment by marmottin** [comment] 2015-10-18 11:54
Doesn't work for me either (W7 x64).

Also, there seems to be an update (1907) but the updater keeps downloading the current one (1891).

**Comment by Murd3rTr0n** [comment] 2015-10-18 16:25
Hey, yeah wanted to include specs (can't believe I didn't before.)
AMD Phenom X4
AMD HD6870 Catalyst 15.7.1
Win 7 x64

So yeah, I also wanted to say that I did a fresh unpack of the zip too,
rather than update through the app, and it still wouldn't allow any games
to start.

**Comment by SnowRay** [comment] 2015-10-18 20:17
Confirmed, even with the latest update. And now Battle.net app itself just hangs when starting :)

**Comment by navjack** [comment] 2015-10-18 21:03
yeah EVERYTHING hangs honestly. like i said it just hooks into erryting that it wants to. can't even run it.

**Comment by Formyndare** [comment] 2015-10-19 13:58
+1 to this, program is acting more like a rootkit than its original function.

**Comment by PeterTh** [comment] 2015-10-19 17:39
It's original function is already acting like a rootkit ;)
That is, it always injects itself into everything, it's just that it should immediately un-inject itself again if it figures out that the executable is not on the whitelist. Which is what it still does for me, and as I said I didn't change anything regarding the code :/

It's possible that the behavioral changes are due to compiling the latest version with Visual Studio 2015 on Windows 10. But if that is the case, I really don't know why or how to change that.

For now, if you are affected, yo ucan download any old build of the .dll from github by navigating to that commit. (Of course, you shouldn't update then, and you might run into .ini incompatibilities)

E.g. here's a commit before any of the resent changes: https://github.com/PeterTh/gedosato/...0eeb78f66/pack

**Comment by karasuhebi** [comment] 2015-10-19 17:42
I'm on Windows 8 and I'm experiencing issues.

**Comment by navjack** [comment] 2015-10-19 18:31
you just... download that commit as a zip? i don't know really how to use these things, why can't it just be a link to a zip file or something and i just have it.

**Comment by PeterTh** [comment] 2015-10-19 18:48
Following this discussion:
Karasuhebi: I just posted on the thread. It's happening to me on Windows 8. Need me to test anything for you?
> Karasuhebi: I can also make my computer available to you if you want. Pick your poison: VNC, RDC, TeamViewer.
> Durante: hmm, you could try something for me
> Karasuhebi: Shoot
> Durante: close GeDoSaTo and every affected application
> Durante: then get DebugView: https://technet.microsoft.com/en-us/library/bb896647.aspx
> Durante: and run that as admin
> Durante: (tell me when you are ready with that)
> Karasuhebi: Is it necessary to close every affected application? I don't even know if I'm aware of all of them lol
> Durante: well, it shouldn't really
> Durante: I'll see in the output if it was affected
> Durante: we can give it a try anyway
> Karasuhebi: Okay
> Durante: so, you run debugview as admin
> Durante: then minimize it (yes, this is actually important ;))
> Durante: then you start the latest version of GeDo
> Durante: then you start some application which shouldn't be intercepted, like notepad or calc
> Durante: then you close taht application
> Durante: then you close GeDo
> Durante: and then you re-open the DebugView window and tell me what it says
> Karasuhebi: Okay
> Karasuhebi: Would it be better if I try opening an application that I know for a fact crashes when GeDoSaTo is open?
> Karasuhebi: Or do you want me to do notepad?
> Durante: no, it's actually better if it doesn't crach
> Durante: crash
> Karasuhebi: Okay
> Durante: the crash is a result of something going wrong earlier
> Karasuhebi: OK so it says SHIMVIEW: ShimInfo (Complete)
> Karasuhebi: GeDoSaTo: startup
> Karasuhebi: GeDoSaTo: Got install dir
> Karasuhebi: That's it
> Durante: hmmmmmm
> Karasuhebi: Notepad didn't crash.
> Durante: there's a lot of stuff completely missing in the log :/
> Karasuhebi: Oh great
> Karasuhebi: Well actually I just noticed I'm on build .1891 and GeDoSaToTool is telling me there's a .1907
> Karasuhebi: Let me update and try again. Sorry.
> Karasuhebi: Wasn't aware you did another build.
> Durante: even with the old one there should be more, but the latest gives full information about the interception process
> Karasuhebi: You should really make that update text pop. Maybe add some color to it :P
> Karasuhebi: Okay so..update to latest or no?
> Durante: yes, then try the whole thing again
> Karasuhebi: ok
> Karasuhebi: so let me close out of DebugView
> Karasuhebi: Oh balls
> Karasuhebi: It crashed haha
> Karasuhebi: Damnit GeDoSaTo :P
> Karasuhebi: I'm seeing a lot of shit in here now though
> Karasuhebi: GeDoSaTo: Got install dir
> Durante: did you minimize it?
> Karasuhebi: GeDoSaTo: blacklisted / not...
> Karasuhebi: No I was about to close out of it
> Karasuhebi: Like I had the window up
> Karasuhebi: check it out: http://i.imgur.com/4tQy44p.png
> Durante: yo uneed to keep the window of Debugview minimized the entire time you have GeDoSaTo active
> Durante: it's just one of those things :P
> Karasuhebi: Okay
> Durante: what you posted is already interesting
> Durante: try it again with the latest version, and the window minimized the whole time
> Karasuhebi: loop?
> Karasuhebi: Hm
> Karasuhebi: it says 1891 still
> Karasuhebi: like that other person said
> Karasuhebi: (after the update)
> Durante: yeah, this is another ymptom of the same issue
> Durante: it can't update the dll while it's in use
> Durante: and the dll is in use because it's still injected when it shouldn't be any more
> Karasuhebi: Gotcha
> Karasuhebi: So download from the website then?
> Durante: you can try renaming the dll
> Karasuhebi: Okay
> Durante: and then updating
> Karasuhebi: ha
> Karasuhebi: looks like that's working
> Karasuhebi: when I clicked the update button I'm getting this: http://i.imgur.com/g55X8fu.png
> Karasuhebi: Can I pick my old dir?
> Karasuhebi: Or is it going to nuke my _user.ini files?
> Durante: just pick a completely new dir
> Karasuhebi: ok
> Durante: for a temporary installation to test this
> Karasuhebi: okie doke
> Karasuhebi: yep, I'm on 1907 now
> Karasuhebi: time for DebugView. Let me close out of GeDoSaTo
> Karasuhebi: okay ok
> Karasuhebi: okay so:*
> Karasuhebi: http://i.imgur.com/Euuj5yQ.png
> Karasuhebi: opened DebugView as admin, minimized. Opened GeDoSaTo as admin, opened Notepad, closed Notepad, closed GeDoSaTo.
> Karasuhebi: Those were the steps.
> Durante: very strange
> Durante: the whole notepad launch is missing
> Karasuhebi: Interesting.
> Karasuhebi: Should I try another program?
> Karasuhebi: maybe GeDoSaTo somehow knows not to hook into programs that come from system32 or something to that effect?
> Durante: no
> Durante: it really only checks the name
> Karasuhebi: I see
> Karasuhebi: Okay just did it again with calc
> Karasuhebi: No line in DebugView mentioning calc
> Karasuhebi: I get all the same lines except it's missing that 4th one that says GeDoSaTo: Tool mode
> Durante: actually, I just tried and notepad really isn't mentioned for some reason
> Karasuhebi: And also the 5th one that says Exiting from GeDo...
> Karasuhebi: Okay I'll try something that's not baked into Windows.
> Karasuhebi: Okay now I'm seeing new stuff. Nothing about the app I opened though.
> Karasuhebi: http://i.imgur.com/dmqB2r2.png
> Karasuhebi: I opened TeamSpeak 3, by the way.
> Durante: http://abload.de/img/debugytu5z.png
> Durante: this is what should happen
> Durante: (SciTE is the program I launched)
> Durante: You can ignore anything not starting with "GeDoSaTo:", that's from other programs
> Karasuhebi: Gotcha
> Karasuhebi: Now I'm wondering what the hell shimview is lol
> Karasuhebi: Looks like some Windows Compat. thing.
> Durante: I actually looked that up a few minutes ago
> Durante: it's some kind of compatibility tool from windows
> Karasuhebi: Yeah
> Durante: it's interesting, since it apparently loads GeDoSaToTool for you, but not for me
> Karasuhebi: Also you're right, the libpng warnings are not for GeDoSaTo. Just launched TeamSpeak 3 by itself and I get the same warnings.
> Durante: it's very very strange that you don't get any messages from GeDoSaTo
> Karasuhebi: Yeah :-\
> Durante: (outside of when it is loaded into GeDoSaToTool)
> Karasuhebi: And what do you mean it's not loading GeDoSaToTool for you? I see it in your screenshot
> Karasuhebi: Or is that an old screenshot?
> Durante: no, I meant that *ShimView* isn't loading for me when I start GeDoSaToTool
> Karasuhebi: Oh
> Durante: but for you, Windows seems to decide that it's necessary
> Karasuhebi: That is interesting.
> Karasuhebi: I just checked the Compatibility tab in the Properties window for the Tool .exe and there's nothing checkmarked so....I have no idea.
> Karasuhebi: Oh maybe because I run it as admin!
> Karasuhebi: Although I don't know how not to run it as admin. It always asks me.
> Durante: in any case, it shouldn't really matter
> Durante: the insane part is how it can even do anything on your system if it doesn't get hooked (which it apparently doesn't, judging from the DebugView outptu)
> Durante: can you do a counter-check with the previous version I linked on github?
> Durante: and see what that gives you in the log?
> Karasuhebi: Sure
> Karasuhebi: BTW I went ahead and tried this DebugView process with qBittorrent which I know crashes on startup with GeDoSaTo open
> Karasuhebi: and DebugView just goes bananas with GeDoSaTo mesages
> Karasuhebi: blacklisted / not whitelisted
> Durante: can you show me?
> Karasuhebi: exiting from qbittorrent
> Karasuhebi: Sure one sec
> Karasuhebi: http://i.imgur.com/cE5UJ83.png
> Karasuhebi: and on and on
> Karasuhebi: it stops at around line 84 and then it does the same thing with WerFault for a little while.
> Durante: hmmmmmmmmm
> Durante: now this is interesting
> Karasuhebi: http://i.imgur.com/0wiQIVv.png
> Durante: forget about the other check
> Karasuhebi: Okay
> Durante: give me some time to try something instead
> Karasuhebi: Sure
> Karasuhebi: Like I said if you need to try something on my computer, feel free to remote in as well
> Karasuhebi: I don't have an amazing upload speed but it's pretty decent (10Mbps) so there shouldn't really be much lag.
> Durante: http://filehorst.de/d/brmBcrno
> Durante: try replacing the GeDo dll with that one
> Durante: and check the behaviour
> Karasuhebi: ok
> Karasuhebi: success!
> Karasuhebi: It's not crashing qBittorrent :)
> Karasuhebi: Want me to check DebugView though? Just to see what I see?
> Durante: yes, please do
> Karasuhebi: Okay
> Karasuhebi: Yep, I see more stuff now
> Karasuhebi: http://i.imgur.com/AA4uRvH.png
> Karasuhebi: I used MPC-HC this time instead of TeamSpeak 3 just to avoid the stupid libpng warning
> Durante: another thing to check would be what happens if you exit GeDoSaToTool while something (like the torrent client) that you started while it was active is running
> Karasuhebi: Okay I'll try that
> Karasuhebi: That didn't cause a crash before if memory serves. But I'll try that
> Durante: It's now using "Steam mode" on everything :P
> Karasuhebi: What is Steam mode
> Karasuhebi: Is it some non-intrusive way of hooking?
> Durante: actually, more intrusive in a way
> Durante: in normal mode, when gedo figures out that it shouldn't run for the given exe, it immediately unloads itself
> Durante: in steam mode, it just goes completely inactive, and only really unloads when you close gedosatotool
> Karasuhebi: http://i.imgur.com/XT2ySAO.png <-- opened GeDo, opened qBT, closed GeDo
> Durante: looks fine
> Karasuhebi: Yep
> Karasuhebi: So then why is it working? Is there an issue with unloading that causes programs to hang?
> Karasuhebi: Kinda looks like an infinite loop
> Durante: my assumption I got from your log was that it successfully unloads itself
> Durante: but that the dll is then immediately loaded again
> Durante: and so on and so forth
> Durante: which blocks the process from any program
> Durante: process
> Durante: progress
> Durante: whew
> Durante: which makes it unresponsive
> Durante: und which is what people report as crashes
> Karasuhebi: I see
> Durante: the only problem is that I still don't know **why** the old method suddenly stopped working
> Karasuhebi: well did you see my comment on the blog about a commit from May that got merged recently with the other stuff you did?
> Karasuhebi: Maybe it's that commit?
> Karasuhebi: Called "Added d3dswapchain9ex interceptors"
> Karasuhebi: I'm totally guessing.
> Durante: It's not a bad guess, but no, that couldN't change anything with the basic injection process
> Durante: it only matters once we are already really hooked
> Durante: one more thing before I push this as the real new version
> Durante: can you check if it actually works as you would expect it to work for whitelisted games?
> Karasuhebi: Yeah
> Karasuhebi: Want me to keep DebugView open?
> Durante: nah
> Karasuhebi: Alright
> Karasuhebi: Hm...what would be a good game to test
> Karasuhebi: I'll try FF13 and see if the GeDo messages show up at the top.
> Karasuhebi: yep
> Durante: working?
> Karasuhebi: Yeah I see the status messages. Is that good enough?
> Durante: Ok, I'll do a bit more testing on my side and then push it
> Karasuhebi: What you don't trust my testing? :P
> Durante: one more thing, can I include this chat log with the git issue? For future reference
> Karasuhebi: Yeah of course
> Durante: great, thanks!

I just pushed commit https://github.com/PeterTh/gedosato/commit/4dc3fba69b2ce1efd97a1f2223ed13460eed4e8c which unifies injection behavior. I still don't know why the old version suddenly stopped working for some people, but perhaps this will mitigate the issue.

**Comment by PeterTh** [comment] 2015-10-19 19:00
Please let me know if this resolves the problems for you (you might have to reboot and/or install from scratch to update if you were affected).

**Comment by Formyndare** [comment] 2015-10-19 19:32
Testing now!

**Comment by navjack** [comment] 2015-10-19 20:20
i can't launch path of exile. and when i try and remove the dll file it says steam client bootstrapper and corsairlink are using it. fresh install too.

**Comment by Murd3rTr0n** [comment] 2015-10-20 02:25
Rebooted, completely removed GeDoSaTo and installed the 1912 commit and
still no progress. Sorry, I think it's cool you were working on it though.

**Comment by SnowRay** [comment] 2015-10-20 03:35
Yeah, I'm on Win 7 x64, still same abnormal behavior with 1912.

**Comment by slx7R4GDZM** [comment] 2015-10-20 05:04
Have you tried using a different compiler, Peter? I remember the Dolphin-emu project having some issues with VS2015 slightly changing some compiler behavior.

**Comment by karasuhebi** [comment] 2015-10-21 08:12
That's strange. It's working for me. I'll have to try downloading a fresh copy and seeing if it still works for me. I'll get back to you guys tomorrow.

**Comment by galneon** [comment] 2015-10-21 20:32
Because it's easier to reply here than on your moderated blog where my past comments often never escaped the queue if the article was older than a few days, installing the VS 2015 redist made no difference for me.

**Comment by navjack** [comment] 2015-10-21 21:28
yeah i think its the windows 10 compatability or something... the way it
was compiled before was great but this new one. eh.

**Comment by navjack** [comment] 2015-10-21 21:29
isn't this mostly happening on us windows 7 peoples?

**Comment by Formyndare** [comment] 2015-10-21 21:38
Windows 7 here, yes

**Comment by Murd3rTr0n** [comment] 2015-10-21 21:46
Win 7 Pro x64 yeah

**Comment by ghost1985** [comment] 2015-10-22 17:12
Windows 7 x64, AMD GPU here, doesn't work for me either, if it helps, i found that the commit on October 12 is where it stopped working (d298740), the previous commit (45004c1) is working fine.

**Comment by karasuhebi** [comment] 2015-10-22 17:36
>you just... download that commit as a zip? i don't know really how to use these things, why can't it just be a link to a zip file or something and i just have it.

@navjack The old GeDoSaTo.dll file is right there. Just click on it to download and place in your GeDoSaTo folder.

>installing the VS 2015 redist made no difference for me.

@galneon Did you make sure to install the redist for Visual C++? There's more than one Visual Studio 2015 redistributable.

**Comment by galneon** [comment] 2015-10-22 17:42
@karasuhebi I should have been more specific.  Yes.

You seem to be the only person with Windows 8.1 who has been vocal about experiencing the problem, and the only person with any OS for whom the recent commit fixed the problem...

**Comment by navjack** [comment] 2015-10-22 17:44
Just roll that one commit that was mentioned a couple posts ago into a
windows 7 only build please. Have the updater check the OS and then only
download that one working one.

**Comment by karasuhebi** [comment] 2015-10-22 17:50
@galneon Looks like it's a Win7 problem, yeah. That sucks. :-\

@navjack I'm not sure he can do that though. It looks like the problem stems from building GeDoSaTo using VS 2015 and if he were to roll back the changes from that commit, I would assume that he couldn't build it in VS 2015 anymore. The old .dll file is still there, just grab that one while he figures out a fix for this. He mentioned in his latest article that he was going to try a fix this weekend. Let's see how that goes!

**Comment by navjack** [comment] 2015-10-22 17:54
Ah okay. Sounds good.

**Comment by PeterTh** [comment] 2015-10-25 16:27
I implemented the completely new injection behaviour this weekend, please test it.
(More infoermation: http://blog.metaclassofnil.com/?p=770)

**Comment by galneon** [comment] 2015-10-25 17:07
After testing with several games, I can say it seems to be working perfectly for me again. :)  Thanks for all your work on this.

**Comment by PeterTh** [comment] 2015-10-25 17:18
Whew, that's what I wanted to hear.

Wonderful!

**Comment by Murd3rTr0n** [comment] 2015-10-25 17:22
I can also confirm that this build is now working like it did before.

Win 7 Pro x64
AMD Phenom x4
AMD HD6870

Also, I know this isn't the place, so I'll be quick, but can anyone point
me in the right direction to talk to people about custom depth plugins or
downsampling for games that just don't want to behave? I'm looking at you
TERA and Blade&Soul >_>

**Comment by marmottin** [comment] 2015-10-25 17:29
It's working again for me too (W7 x64) :D
Thanks!

**Comment by PeterTh** [comment] 2015-10-25 17:32
Great, closing the issue.

**Closed** 2015-10-25 17:34 UTC

**Comment by karasuhebi** [comment] 2015-10-25 19:42
Congrats on the fix!

**Comment by SwinglesMan** [comment] 2015-10-25 19:47
Doesn't seem to be working for me. Win7 64bit here. Just tried downloading new version, same thing, not working in any game. No startup dialog either.

**Comment by karasuhebi** [comment] 2015-10-25 19:49
What if you perform a new install?

**Comment by galneon** [comment] 2015-10-25 19:51
If it isn't working for you, it's almost certainly because the updater isn't replacing the .dll because the .dll is still in use.  Restart your system (ensuring GeDoSaTo isn't set to run at startup) and run the updater.  You could also install to a brand new location and run it from there instead.

**Comment by SwinglesMan** [comment] 2015-10-25 19:57
Nope, installed to a new location, still no new resolutions. I'm testing out Vanilla SF4 where it always worked without any modification. And yes I put it in the user whitelist.

Using nvidia driver 353.62. Don't think Nvidia is blocking it do you?

**Comment by galneon** [comment] 2015-10-25 20:07
No.

**Comment by SwinglesMan** [comment] 2015-10-25 20:11
Whelp, just reinstalled the visual studio 2015 thing just to make sure and still nothing :(  I saw this thread because I was searching for it since I heard ffxiii text bug got fixed again and that's when I noticed.

**Comment by karasuhebi** [comment] 2015-10-25 20:23
What's the FFXIII text bug?

Have you tried copying the two .dll files from the new install into the folder of the old install? Maybe when you installed in a new location you still opened the GeDoSaToTool.exe from the old location?

**Comment by SwinglesMan** [comment] 2015-10-25 20:26
Nope, old version doesn't work anymore either. And nope, it was launching exactly from where I was launching it from.

**Comment by navjack** [comment] 2015-10-25 20:26
It's working for me now too

**Comment by karasuhebi** [comment] 2015-10-25 20:48
>Nope, old version doesn't work anymore either.

Damn, that sucks. I guess we'll have to wait for @PeterTh to weigh in. In the mean time though, I'd still like to know what the FFXIII text bug is. :)

**Comment by SwinglesMan** [comment] 2015-10-25 20:52
But u already know. Youve been a part of that convo b4 :P

**Comment by ZedGates** [comment] 2015-10-26 13:09
Latest version is working for me, thanks Durante!.

**Comment by karasuhebi** [comment] 2015-10-27 13:56
>But u already know. Youve been a part of that convo b4 :P

Oh is it the one mentioned in #268?

**Comment by cgerlach41** [comment] 2015-10-28 21:31
I too had the problem that i couldn't run any game after the last update. It also showed that there was a new version available, although i updated right before that. In my case it was because the updater updated everything except the GeDoSaTo.dll, because for some reason it was still in use and couldn't even be removed manually. What worked for me was to reboot the system and manally replace the DLL from the newest one from the git, before starting the tool again.

The new version now seems to work like a charm. Thanks for still putting so much work into the tool Peter. It really puts my 980ti to good use, and makes especially older games so much more enjoyable.

**Comment by jsangeorzan** [comment] 2015-10-29 01:46
I fully did the following:
 - Rebooted
 - Deleted entire Folder/uninstalled
 - Downloaded latest version and installed to new folder
 - Ensured I had latest VC Libraries (x64 and x86)

Still can't get it to hook for some reason.  Any thoughts?

Windows 10 x64

**Comment by MSxDOS** [comment] 2015-10-31 17:32
Same here on Win 7 x64, doesn't hook at all. Downgraded to 1884.
